# docker-compose.yml
services:
  backend:
    build: 
      context: ./backend
    container_name: snip_backend
    restart: always
    volumes:
      - ./snip_data:/app/data

  frontend:
    build: 
      context: ./frontend
    container_name: snip_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  snip_data: